language: node_js
node_js:
- stable
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIL6PTU3JZN6HBWHQ
  secret_access_key:
    secure: iB91IV6+5+GhaGWPckqOWJvJ4/JbsLZslZmQvgLcCK+VTPCYj0lgilU/SbUMyPk5ugwhxZ2iWEUB/9dKXvNeyfAG9IixxPrijtGAUyDT8Uw9B9rOMpiedA8t/RPyuyqFGpze0JJAEcVHI9IZD+dR7848xy14I6fL/p209T99W1FdN2D5DygxupfJCGBloSOaf1H9CDo9xD17nDSrELfCe3hZ/bX25YWuTWskPSkuElct4zrQ6hn3Y6POlUy3lU1MJNa54Nksjyt/t1TEiO/ZjO7l01YEguNHcBgB2EaKDKabqBiLOmcUum5YY23YDQTmpM0H6PPwTzkvJljeGrDIvhWY5yfVdl+FKj80RKP9RPBldT08MEMsBOUZnVgZALP/YvZqoY0u+ze+t01kQvNNoNnQt7+Ut7Ej0oo9MNEiMnQSHmdExZFealubjBpOG7CjRi/lPj9FiVZ52RwZwVlYAaYljkoXJ2Dzi6FiKM0BIokZvVqEpolQNRBX7je9RF5VVckpeImjyOEkE9QBQp2kr9mqnVYDffnqMMjFI/6TVNO4tlDb+J129Qlsb8knZoZrYt8ZyC/HEGRxnBaVpin3t2tL0MndYy5mxFaEX0ECU9HcE2pX+t0MRsuqy/7863aheWgRqBSKjMdhvpgFXug7BgLppvK6RCEuUMEkzu3n/cA=
  bucket: kathryn-newbould
  local-dir: "./build/"
  acl: public_read
  on:
    repo: KathrynN/kathryn-newbould-personal-website
    branch: travis-integration
